[WIP] mysql_user: reinitialize the privs list in privileges_unpack()
ansible-collections/ansible.mysql pull request #137
Opened 2021-04-04 17:48 UTC by parseword

##### SUMMARY
In some scenarios, `privileges_unpack()` called `privs.append()` inside a loop without first emptying or reinitializing the `privs` list from the prior iteration. This could result in an invalid `GRANT` statement, which incorrectly included privileges from a previously-built `GRANT` statement.

Reinitialize `privs` on each pass of the loop to prevent this from occurring.

Fixes #136

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
mysql_user

2021-04-04 18:30 UTC, parseword commented
Ready for review

2021-04-05 05:25 UTC, Andersson007 commented
@parseword thanks for the PR!
We have CI tests for the module stored in `tests/integration/targets/test_mysql_user/tasks/`. Could you please cover the case there (just add the task(s) to somewhere which failed before the fix and now works)

2021-04-06 00:23 UTC, parseword commented
That's wading into uncharted territory for me, but I'll give it a shot tomorrow. I think I can put something together by cribbing from the `test_priv_append.yml` task.

2021-04-06 05:34 UTC, Andersson007 commented
ok, if any questions, feel free to ask

2021-04-09 17:17 UTC, Jorge-Rodriguez commented
@parseword if you feel more confident covering this bug fix with a unit test instead, we have those stored in `tests/unit/plugins/modules`

2021-04-10 05:09 UTC, Andersson007 commented
@parseword do we have any time estimates? I'm asking because We're gonna release 2.0.0 next week.
We could wait until you finish this.
If you need more time, no problem, no rush, we could release without this fix and include it in 2.0.1 shortly after. What do you think?

2021-11-20 08:44 UTC, Jorge-Rodriguez requested changes
@parseword Can you add tests for this?

2021-11-20 12:01 UTC, Jorge-Rodriguez commented
@parseword The code patched in this PR has been moved to `/plugins/module_utils/user.py`

2021-11-20 12:17 UTC, Jorge-Rodriguez commented
I reviewed this more closely and after we removed the static check for valid privileges this issue has disappeared as we never read the `privs` list in the `privileges_unpack` function. My [comment](https://github.com/ansible-collections/community.mysql/issues/136#issuecomment-974640869) on issue #136 still applies.

2021-11-20 12:17 UTC, closed without merging