[WIP] mysql_replication: Add aliases to "master" options, add alternatives to "master" state options, add announcement
ansible-collections/ansible.mysql pull request #150
Opened 2021-04-16 12:45 UTC by Andersson007

##### SUMMARY
Relates to https://github.com/ansible-collections/community.mysql/issues/145

mysql_replication:
1) add aliases to "master_" options
2) add alternatives to "master" choices of  `state` options
3) add deprecation warnings and announcement

Important: this does NOT contain any breaking changes. I ran the not touched tests with the changes - they passed. Then changed, the changed ones also passed (but you can recheck if any doubts, just checkout to the first commit of the PR).

2021-04-19 05:53 UTC, Andersson007 commented
CC @Jorge-Rodriguez @bmalynovytch

2021-04-19 06:58 UTC, Jorge-Rodriguez requested changes

2021-04-19 06:58 UTC, Jorge-Rodriguez commented on plugins/modules/mysql_replication.py
> +    - Same as the MASTER_AUTO_POSITION mysql variable.
```suggestion
    - Same as the C(MASTER_AUTO_POSITION) mysql variable.
```

2021-04-19 06:58 UTC, Jorge-Rodriguez commented on plugins/modules/mysql_replication.py
> +    - Same as the MASTER_DELAY mysql variable.
```suggestion
    - Same as the C(MASTER_DELAY) mysql variable.
```

2021-04-19 07:18 UTC, Andersson007 commented
@Jorge-Rodriguez thanks, committed, ready for review

2021-04-19 07:50 UTC, Jorge-Rodriguez approved these changes

2021-04-20 09:50 UTC, bmalynovytch approved these changes

2021-04-20 13:58 UTC, merged

2021-04-20 13:58 UTC, Andersson007 commented
@Jorge-Rodriguez @bmalynovytch thanks for reviewing!