switch "PRIMARY" to "MASTER" on description
ansible-collections/ansible.mysql pull request #573
Opened 2023-09-16 09:00 UTC by lkthomas

switch "PRIMARY" to "MASTER" on the description; the actual code is correct but the documentation is wrong.

2023-09-16 09:00 UTC, lkthomas commented
Related discussion: https://github.com/ansible-collections/community.mysql/issues/571

2023-09-20 11:13 UTC, laurent-indermuehle requested changes
Thanks for your PR. Good catch on the wrong SQL examples.
I'll merge after you approve my addition of the missing word "STATUS" in the getreplica option. Better fix all exemple in one shot ;)

2023-09-20 11:13 UTC, laurent-indermuehle commented on plugins/modules/mysql_replication.py
>        C(getreplica) (SHOW REPLICA),
```suggestion
      C(getreplica) (SHOW REPLICA STATUS),
```

2023-09-20 12:57 UTC, laurent-indermuehle approved these changes

2023-09-27 07:28 UTC, laurent-indermuehle commented
@lkthomas Hi! Yesterday I did something weird, I did a PR on your PR. Don't know if it worked and if you go the notification.
I'm waiting for your reply to merge this PR (after you merged mine)

2023-09-27 07:45 UTC, lkthomas commented
no I don't see any notification

2023-09-27 07:46 UTC, lkthomas commented
oh hang on, I think I know what you mean, 1 second

2023-09-27 07:48 UTC, lkthomas commented
done, check now

2023-09-27 12:16 UTC, Andersson007 commented
@lkthomas could you please remove the changelog fragment, it's not needed for docs only changes

2023-09-27 14:50 UTC, laurent-indermuehle commented
> @lkthomas could you please remove the changelog fragment, it's not needed for docs only changes

oups, my bad. I keep forgetting.

2023-09-28 01:16 UTC, lkthomas commented
sorry which changelog fragment? any screenshot?

2023-09-28 06:26 UTC, laurent-indermuehle requested changes

2023-09-28 06:26 UTC, laurent-indermuehle commented on changelogs/fragments/mysql_replicationi_fix_sql_examples.yml
This file is the changelog. Sorry I added it, should have known better. Please delete it.

2023-09-29 07:34 UTC, laurent-indermuehle commented on changelogs/fragments/mysql_replicationi_fix_sql_examples.yml
@lkthomas I pointed the file that needs to be deleted. Thanks for the work and your contribution!

2023-10-03 08:47 UTC, Andersson007 commented on changelogs/fragments/mysql_replicationi_fix_sql_examples.yml
@laurent-indermuehle i think you could just delete the file in the WebUI and merge

2023-10-03 17:27 UTC, laurent-indermuehle commented on changelogs/fragments/mysql_replicationi_fix_sql_examples.yml
@Andersson007 I can't do that, Github doesn't let me because the file is in @lkthomas's fork :(

2023-10-10 07:53 UTC, laurent-indermuehle commented on changelogs/fragments/mysql_replicationi_fix_sql_examples.yml
Hi @lkthomas, this is a friendly reminder that I'm waiting on your deletion of the fragment file in your fork. When it's done we will be able to merge your contribution.

2023-10-11 07:07 UTC, Andersson007 approved these changes

2023-10-12 11:49 UTC, laurent-indermuehle approved these changes

2023-10-12 11:50 UTC, laurent-indermuehle commented
@lkthomas I'm merging your PR now. Thanks again for your contribution!

2023-10-12 11:50 UTC, merged